---
- hosts: webservers
  sudo: yes
  vars:
    http_port: 80
    doc_dir: /ansible/
    doc_root: /var/www/html/ansible/
    max_clients: 5

  vars_prompt:
    - name: username
      prompt:  What is your name?  What is your Quest?  What is your fav color?

  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Ensure Apache in installed
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"

  - name: Start Apache Services
    service: name=httpd enabled=yes state=started
    when: ansible_os_family == "RedHat"

  - name: Start Apache Services
    service: name=apache2 enabled=yes state=started
    when: ansible_os_family == "Debian"

  - name: Deploy configuration File
    template: src=templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
    when: ansible_os_family == "RedHat"
    notify:
      - Restart Apache


  - name: Deploy configuration File
    template: src=templates/httpd.j2 dest=/etc/apache2/conf-enabled/httpd.conf
    when: ansible_os_family == "Debian"
    notify:
      - Restart Apache

  - name: Copy Site Files
    template: src=templates/index.j2 dest={{ doc_root }}/index.html

  handlers:
     - name: Restart Apache
       service: name=httpd state=restarted

- hosts: dbservers
  sudo: yes

  tasks:
  - name: Ensure MySQL is installed
    yum: name=mysql-server state=present
    #when: ansible_os_family == "RedHat"

  - name: Start MySQL
    service: name=mysql state=started

- hosts: webservers:dbservers
  sudo: yes

